services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./cars_data.sql:/docker-entrypoint-initdb.d/cars_data.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://myuser:mypass@db:5432/mydb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - "8005:3000"

volumes:
  db_data:
