name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (optional)
        run: |
          python -m pip install --upgrade pip

      - name: Install project requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          # Ensure testing deps present
          pip install pytest httpx

      - name: Run tests
        run: |
          pytest -q
